### ISSUE TITLE
Processing continues while kapitan waits for gpg unlock key

### ISSUE THREAD

**Issue by ademariag** [deepmind/kapitan#129]
Currently when running `kapitan compile`, if gpg password is needed, the compilation for other targets will continue on the background making it difficult for a user to understand that entering the password is needed.

Eventually kapitan will error out with "encryption incomplete"

We should have a strategy to check if keyring is open/closed before compiling targets, or at least make it easier to enter the password.

**Comment by yoshi-1224** [comment]
Hi @ademariag @uberspot 
I don't think it is easy to modify the behaviour of the gpg-agent and pinentry prompt, but what we can do is to **terminate early** with error when the passphrase is not cached.

In kapitan, we use python-gpg module that wraps around gpg executable. When we perform secret encryption, the corresponding command is (stripping away the kwargs and assuming asymmetric encryption):
`gpg  --recipient <recipient> -e <data>`
This by default has `--pinentry-mode=ask`, which prompts the user for passphrase should it not be cached.

What we can do is to explicitly set `pinentry-mode` to `error`. This will prevent pinentry prompt from popping up, and:
1. if passphrase is cached => encrypts/decrypts successfully
2. if passphrase is NOT cached => fails straight away

I've tested this with `gpg` CLI as well as `kapitan compile` by modifying the `python-gpu` code directly as PoC.

One complication is that I am not sure if this work on other machines, so probably requires a bit more testing on different OS (I'm on Ubuntu 18.04). 

Do you think this is a useful solution?

**Comment by harsh-98** [comment]
I try running `kapitan compile` with my password and password_256 deleted for kubernetes mysql example.  
And it waited for password on my system. @ademariag Is this issue valid now?

Also @yoshi-1224 , the problem with failing when the passphrase is not cached, is that user will have to run gpg command manually, so that system can cache the passphrase. And then run kapitan compile.

**Comment by yoshi-1224** [comment]
@harsh-98 

> I tried running `kapitan compile` with my password and password_256 deleted for kubernetes mysql example.
> And it waited for passphrase on my system. @ademariag Is this issue valid now?

Yes, this is exactly what I experienced as well, which I believe is preferred for some users but not for others?

> Also @yoshi-1224 , the problem with failing when the passphrase is not cached, is that user will have to run gpg command manually, so that system can cache the passphrase. And then run kapitan compile.

Yes I know, because I've looked into this. In fact this is the exact point @ademariag is bringing up. The issue I found is that it is hard to know in advance whether a passphrase is cached or not (because there is no such interface, or even if there is, can be inconsistent across systems), and that's why I proposed the solution above. 

Do you think there might be a better way to handle this?

**Comment by yoshi-1224** [comment]
@harsh-98 Actually, I agree with you that this might no longer be an issue, because I also noticed that the prompt does wait for the user to enter the passphrase!

**Comment by adrianchifor** [comment]
I tried again and couldn't replicate this on macOS nor Linux, kapitan behaves as expected and waits for input from gpg pinentry. Will close for now. If anyone encounters this please re-open and give an example.
