### ISSUE TITLE
Warn user when mismatch between target mentioned in yml and the name of the target yml file

### ISSUE THREAD

**Issue by uberspot** [deepmind/kapitan#203]
**Describe the bug/feature**
When the target mentioned in a yml file is different than the name of the target yml file itself you might get compilation errors like ` Jsonnet error: failed to compile ... `

**To Reproduce**

1. Go to a yaml under inventory/targets
2. In one of the target yml files: change the value of `parameters.target_name to something different than the name of the actual yaml file.
3. Try to compile.

**What happens**

Errors like ` Jsonnet error: failed to compile ... `, compilation fails without fully indicating why.
 
**Expected behavior**
An error/warning is printed to easily identify issue.

**Comment by yoshi-1224** [comment]
Hi,

I went through the codebase and found that `load_target_inventory` function in `targets.py` is a good place to do the check, since we have `targets_list` variable and `inventory_path`. Can I proceed with this idea?

Also, should we throw `InventoryError` (defined in `errors.py`) for such a mismatch, or create another custom error class?

**Comment by uberspot** [comment]
Feel free to proceed. :) I think InventoryError with a custom error message that explains the problem and which file caused it would be helpful enough.

**Comment by yoshi-1224** [comment]
Thanks for the quick reply! I'll be making a PR shortly for this issue.

**Comment by gburiola** [comment]
Instead of doing a check, why not getting rid of the need to define `target_name` inside the yaml file and dynamically creating the variable ?
