### ISSUE TITLE
How to indent (all lines of a) multiline string that is read from a secret?

### ISSUE THREAD

**Issue by frittentheke** [deepmind/kapitan#301]
**Describe the bug/feature**
I required a multiline string, more specifically a RSA private key in PEM format, that is stored in a secret, to be rendered out. The actual use case the template is a yaml file where the certificate is to be placed as YAML scalar block (introduced with a " | "), but it is required  to be indented by 12 characters.

**To Reproduce**
1. Create a multiline string and store it as a secret in gpg format.
2. Reference that secret in a template, i.e. {{ parameters.certificate_key }}
3. try to indent the string using i.e.  {{ parameters.certificate_key | indent(12) }}
4. unfortunately only the first line is indented :-(
Even though Jinja2 indent is to indent every line of a string (http://jinja.pocoo.org/docs/2.10/templates/#list-of-builtin-filters -> indent)

```Return a copy of the string with each line indented by 4 spaces. The first line and blank lines are not indented by default.```

**Expected behavior**
I would expect the fact that an input is sourced from a secret to be transparent to all other modifications one can do using Kapitan build-ins or even added custom Jinja2 functions.

**Additional context**
This is somewhat related to https://github.com/deepmind/kapitan/issues/277 I suppose.

**Comment by uberspot** [comment]
Interesting catch. I'm not sure if this is because of how kapitan treats secrets when revealed or if it's a jinja2 issue, so some more questions:

1. When you encrypt/create the secret with kapitan, what command do you use exactly?
2. If you then try to reveal the secret in command line, is the result still multiline or a single line?

**Comment by ramaro** [comment]
Unfortunately this is because of the way revealing with jinja2 (and other plain output types) works.

Kapitan will compile outputs with secret tags into hashed tags. Revealing for output types generally works by doing a simple search and replace of the compiled item

A jinja2 compilation works as follows:

compile -> jinja2 render -> [compiled items + hashed tags] -> reveal -> [compiled items]

On input types that compile to yaml or json (jsonnet and kadet), this is not a problem since reveal recursively traverses the compiled items and resolves hashtags before converting to yaml/json.

We have 2 possible solutions:

1. When using `kapitan compile --reveal`, reveal should be done before compilation and therefore a jinja2 render will be valid when using filters since these will be done on a revealed tag instead of a hashed tag.
But this will not work when using `kapitan secrets --reveal -f manifest.yml`

2. Implement a new type of secret functions that will be evaluated on reveal only (e.g. base64, indent, etc) which will be independent from the input types.

**Comment by ramaro** [comment]
@frittentheke you should reconsider rewriting your module in Jsonnet/Kadet, where you shouldn't have this limitation.

**Comment by frittentheke** [comment]
@ramaro  is there really no road to a fix to make the secret handling independent from the template language / engine used? Jinja2 is just so popular and really helps to get buy in when introducing templating with Kapitan to others :-)

**Comment by ramaro** [comment]
@frittentheke I can only see this working when using `$ kapitan compile --reveal` where revealing is done in memory before rending any template. Would a solution like this work for you?

**Comment by frittentheke** [comment]
@ramaro that sounds exactly like we would need and actually what I expected the intended workflow to be. We always run _kapitan compile --reveal_ in one shot when we actually require the secrets to be available (the result to by fully rendered).

To be clear: We never do a compile and then afterwards do _kapitan secrets --reveal_ on those half-rendered files.

**Comment by uberspot** [comment]
After discussing a bit with @ramaro how about the following:

We create a jinja function to accommodate this edge case. 
The function can be used with a secret (as part of the pipes) and it will reveal the secret, if the compile (--reveal) argument is set AND the parameter to the function contains a secret reference tag.
So it's as if Jinja is revealing the secret.
If the argument is not set, the function will just do nothing.

Pros:
 + non-intrusive option that covers this use case but doesn't break any others
Cons:
 - might introduce a small performance penalty because when that function is used with the --reveal argument it will decode all secrets when compiling as well.

**Comment by ramaro** [comment]
fixed in #332
