### ISSUE TITLE
Are tests a requirement 

### ISSUE THREAD

**Issue by th31nitiate** [deepmind/kapitan#561]
This is probably something for the slack channel but I currently do not have access to that. I would like to know if tests are a strict requirement for contributing code to Kapitan. I see that the 'gkms' back end does not currently contain any test. This triggered my curiosity as to try understand why that is the case and if it would be a requirement for creating back ends ?

**Comment by uberspot** [comment]
Hi @th31nitiate, :) 

It depends. In general we would highly appreciate tests for most contributions for mainly two reasons:
1) Validating that the contribution actually works before merging
2) Preventing regressions in the future if things/dependencies change

In the past the test code coverage was <40%. Through some focused efforts we improved that to 65%+ so the idea was that for any new code we'd require tests too in an effort to keep the code coverage on a 'decent' level and improve it further. 
Some secret backends like gkms/awskms are difficult to test in a pipeline like travis without requiring external resources like an AWS/GCP account, which we wanted to avoid for an open source project. Mocking is an option but is time-consuming to setup. 

If a code contribution is easy/realistic to test, it makes sense to ask for tests as well. Or at least add them ourselves during review (?). If it's difficult to test because the functionality depends on an external/third-party service and it's also difficult to mock then we can re-evaluate per use-case. 

If you need help with the testing parts, feel free to reach out on slack. :+1:

**Comment by th31nitiate** [comment]
Thank you, that answered my question and concerns.
