### ISSUE TITLE
Bug: Using remote inventory files (still) requires a separate fetch command due to reclass failing on missing classes.

### ISSUE THREAD

**Issue by skinny** [deepmind/kapitan#572]
**this is just a quick write up and I'll try to expand on this tomorrow.**

Using the latest 0.29-rc version :

I would really like to see that running a `compile --fetch` once would download the remote files and be able to use them afterwards in the same run as an inventory class.

Downloading the inventory file works fine but referencing the just downloaded file in other places like :

```
classes:
  - stages.dev
  - clusters.k8s-euw-039
  - tentants.customer-x
```
breaks the compile process because the file 'customer-x' is not present (yet). After running the `inventory` command the file exists and the compilation succeeds.

Another idea that I had was that it would be great to also be able to fetch remote 'targets' where the target file is generated/served by an external system instead.

**Comment by uberspot** [comment]
>> Another idea that I had was that it would be great to also be able to fetch remote 'targets' where the target file is generated/served by an external system instead.
This is definitely interesting, but might be better suited in a separate issue. :) 

The rest does seem like a valid bug where fetched inventories aren't loaded yet into kapitan (?). cc @AlphaRoy14 

@skinny could you also add a snippet with your kapitan config for the remote inventories if they're public urls? To help debug.

**Comment by AlphaRoy14** [comment]
If the configuration is something like:
```yaml
classes:
  - stages.dev
  - clusters.k8s-euw-039
  - tentants.customer-x # not currently in the classes directory but will be created if inventory fetch is successful 
parameters:
    kapitan:
        inventory:
            - type: git
               output_path: xyz
               source: xyz
```
Then kapitan would throw an error since we are using reclass in the load_target_inventory() function. All the classes must be present for reclass to work without any error.
https://github.com/deepmind/kapitan/blob/bbe0979391a23a311c506209ca8d899d8864c18b/kapitan/targets.py#L100
https://github.com/deepmind/kapitan/blob/bbe0979391a23a311c506209ca8d899d8864c18b/kapitan/targets.py#L334

It does make sense to have classes declared before they are fetched. So for that, we can do something like:
- Define a function in `/kapitan/kapitan/resources.py` similar to inventory_reclass() https://github.com/deepmind/kapitan/blob/bbe0979391a23a311c506209ca8d899d8864c18b/kapitan/resources.py#L294
except it will not raise an error if a class does not exist. Finally, when all the inventory items are fetched, we can run the original inventory_reclass() to get the entire inventory mapping. However, I'm not yet sure if this can be done without changing anything in reclass.
- Define all the remote inventories in the target files only so that we just parse the target yamls to get the inventory key and not check the classes. Finally, use inventory_reclass() to map the inventory.
- any other options? @uberspot

**Comment by uberspot** [comment]
You are actually very close to the proper solution, but instead of a new function like inventory_reclass you just need to make [one flag](https://github.com/salt-formulas/reclass/blob/develop/README-extensions.rst#ignore-class-not-found) in it configurable. :) 

---------------------------------

So yes, this bug is due to how in targets.py (L 100) we do the following: 

```
try:
        target_objs = load_target_inventory(inventory_path, updated_targets)

        # append "compiled" to output_path so we can safely overwrite it
        compile_path = os.path.join(output_path, "compiled")
        worker = partial(..............
        )

        if not target_objs:
            raise CompileError("Error: no targets found")
        if kwargs.get("fetch_inventories", False):
            # new_source checks for new sources in fetched inventory items
            new_sources = list(set(list_sources(target_objs)) - cached.inv_sources)
            while new_sources:
                fetch_inventories(
                    inventory_path, target_objs, dep_cache_dir, kwargs.get("force_fetch", False), pool
                )
                cached.reset_inv()
                target_objs = load_target_inventory(inventory_path, updated_targets)
                cached.inv_sources.update(new_sources)
                new_sources = list(set(list_sources(target_objs)) - cached.inv_sources)
```

Either the first, or the second call to load_target_inventory, can fail if any of the classes referenced there doesn't yet exist (before getting fetched). 

Another useful point is that reclass already has an option to ignore classes that don't exist. https://github.com/salt-formulas/reclass/blob/develop/README-extensions.rst#ignore-class-not-found
That is false by default, and that's preferred. But in the case where you use `--fetch` it makes sense to set this reclass flag to True for the first and second call to load_target_inventory. Then we might have to call load_target_inventory one last time after this code block ^ to make sure that after fetching all remote inventories, we can now load the entire inventory without any classes missing.

Something like this for example: 
```
try:
        target_objs = load_target_inventory(inventory_path, updated_targets) # with ignore_class_notfound: True

        # append "compiled" to output_path so we can safely overwrite it
        compile_path = os.path.join(output_path, "compiled")
        worker = partial(
            compile_target,
            search_paths=search_paths,
            compile_path=temp_path,
            ref_controller=ref_controller,
            inventory_path=inventory_path,
            **kwargs,
        )

        if not target_objs:
            raise CompileError("Error: no targets found")
        if kwargs.get("fetch_inventories", False):
            # new_source checks for new sources in fetched inventory items
            new_sources = list(set(list_sources(target_objs)) - cached.inv_sources)
            while new_sources:
                fetch_inventories(
                    inventory_path, target_objs, dep_cache_dir, kwargs.get("force_fetch", False), pool
                )
                cached.reset_inv()
                target_objs = load_target_inventory(inventory_path, updated_targets) # with ignore_class_notfound: True
                cached.inv_sources.update(new_sources)
                new_sources = list(set(list_sources(target_objs)) - cached.inv_sources)

           # If --fetch, then load inventory one last time and make sure ignore_class_notfound: False
           target_objs = load_target_inventory(inventory_path, updated_targets)
```

The ignore_class_notfound option is set here https://github.com/deepmind/kapitan/blob/master/kapitan/resources.py#L294 
So if you just make that configurable, and then change it when the --fetch flag is set, I think it would solve this issue. 
It might make compiling slightly slower when you use --fetch, because it will have to re-compute the inventory for every remote source as well as one last time at the end, but that's an acceptable tradeoff for now. 

If the --fetch flag is NOT set, then it should be the same as it is now (aka load_target_inventory with ignore_class_notfound: False). 

Does that sound ok?

**Comment by AlphaRoy14** [comment]
Great! thanks for the explanation 👍

**Comment by uberspot** [comment]
I believe this is now fixed in the latest rc and I'll do a full release now too.
Feel free to reopen this bug if this occurs again.
